name: drahkma
description: "Aplicação de gerenciamento financeiro inteligente."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  graphic: ^2.5.0
  http: ^1.6.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_charts: ^33.1.46
  ini: ^2.1.0
  web: ^1.1.1
  shared_preferences: ^2.5.4
  get_it: ^9.2.0
  equatable: ^2.0.8
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.7.0
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
  assets:
    - images/
