name: drahkma
description: "Aplicação de gerenciamento financeiro inteligente."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  graphic: ^2.5.0
  http: ^0.13.6
  intl: ^0.19.0
  requests: ^4.7.0
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_charts: ^27.1.57
  ini: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
  assets:
    - images/
